FROM jupyter/minimal-notebook:d4cbf2f80a2a

ENV SQLFLOW_SERVER localhost:50051

RUN pip install sqlflow numpy

# Add example
RUN wget https://raw.githubusercontent.com/sql-machine-learning/sqlflow/develop/example/jupyter/example.ipynb -O /home/jovyan/example.ipynb

